### PR TITLE
Update name for templatetags library

### LINKED ISSUE #28: {% load staticfiles instagram_client %} breaks django-compressor
I'm trying to deploy my site to Heroku where I intend to use django-compressor on my CSS and Javascript files. I get the following messages when I run `python manage.py compress`.

```
Invalid template /usr/local/lib/python3.7/site-packages/django_instagram/templates/django_instagram/recent_media_wall.html: 'staticfiles' is not a registered tag library.
```

and 

```
Invalid template /usr/local/lib/python3.7/site-packages/django_instagram/templates/django_instagram/recent_media_box.html: 'staticfiles' is not a registered tag library.
```

Is this related to Django 3.x removing `{% load staticfiles %}`? See this [StackOverflow post](https://stackoverflow.com/questions/55929472/django-templatesyntaxerror-staticfiles-is-not-a-registered-tag-library) for info.

Would `{% load static instagram_client %}` be the new, correct syntax?

### PR DESCRIPTION
**Pull request by fsouza**
This fixes compatibility with Django 3, by using static instead of
staticfiles.

Closes #28.

### CODE REVIEW

**Comment by marcopompili** [comment]
Thanks for the PR, but by doing this it means dropping support to versions prior to 3, I already fixed this problem by doing a version check, still I haven't pushed the commit.

**Comment by fsouza** [comment]
Not sure what you mean. `load static` was introduced in 1.10 I think (and Django 1 has reached end of life).

Do you need to support versions older than that?

**Comment by marcopompili** [comment]
Oh I thought this also involved Django 2, good to know. ATM minimum version requirement is `Django >= 1.6`, gonna set this to `1.11` and avoid `staticfiles` completely.

**Comment by fsouza** [comment]
@marcopompili can you push 0.3.2 to pypi? 

Thank you very much for your work! 😁

**Comment by marcopompili** [comment]
It should be out on pypi

**Pull request merged**
